# Generated by Django 5.2.7 on 2025-12-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationAnalysis',
            fields=[
                ('id_corr', models.AutoField(primary_key=True, serialize=False)),
                ('pasangan_variabel', models.CharField(max_length=50)),
                ('nilai_korelasi', models.FloatField()),
                ('tingkat_kekuatan', models.CharField(max_length=30)),
                ('tanggal_analisis', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelMSSA',
            fields=[
                ('id_model', models.AutoField(primary_key=True, serialize=False)),
                ('window_length', models.IntegerField()),
                ('embedding_dimension', models.IntegerField()),
                ('jumlah_komponen', models.IntegerField()),
                ('lag_data', models.IntegerField()),
                ('mse', models.FloatField()),
                ('rmse', models.FloatField()),
                ('mae', models.FloatField()),
                ('akurasi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id_station', models.AutoField(primary_key=True, serialize=False)),
                ('nama_stasiun', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id_pred', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_prediksi', models.DateField()),
                ('pm10_pred', models.FloatField(blank=True, null=True)),
                ('pm25_pred', models.FloatField(blank=True, null=True)),
                ('so2_pred', models.FloatField(blank=True, null=True)),
                ('co_pred', models.FloatField(blank=True, null=True)),
                ('o3_pred', models.FloatField(blank=True, null=True)),
                ('no2_pred', models.FloatField(blank=True, null=True)),
                ('indeks_kualitas_udara', models.CharField(max_length=40)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='API.modelmssa')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='API.station')),
            ],
        ),
        migrations.CreateModel(
            name='PollutantData',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollutant_data', to='API.station')),
            ],
        ),
        migrations.AddField(
            model_name='modelmssa',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelmssa', to='API.station'),
        ),
        migrations.CreateModel(
            name='MeteorologicalData',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('temperatur_minimum', models.FloatField(blank=True, null=True)),
                ('temperatur_maksimum', models.FloatField(blank=True, null=True)),
                ('temperatur_rata', models.FloatField(blank=True, null=True)),
                ('kelembapan_rata', models.FloatField(blank=True, null=True)),
                ('curah_hujan', models.FloatField(blank=True, null=True)),
                ('kecepatan_angin_maksimum', models.FloatField(blank=True, null=True)),
                ('kecepatan_angin_rata', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteorological_data', to='API.station')),
            ],
        ),
        migrations.CreateModel(
            name='MapView',
            fields=[
                ('id_view', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('indeks_kualitas_udara', models.CharField(max_length=20)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_views', to='API.station')),
            ],
        ),
    ]
